#================================================================================================================================================================#
#                                                             Configuring SkyManager Plugin Options                                                              #
#                                                                                                                                                                #
#                                                                                                                                                                #
#                                                                           Version 1.0                                                                          #
#                                                                                                                                                                #
#                                                                                                                                                                #
#                                              You can modify them as you wish, but do not appropriate the plugin !                                              #
#                                                                                                                                                                #
#                                                                                                                                                                #
#                                                                 Plugin develop by CanardConfit                                                                 #
#================================================================================================================================================================#


#This option allows to activate or not the module to see the contents of a file
enable-file-view: true


#This list is the list of extentions that the plugin will not try to read (these examples are extensions that can not be read as a text)
ban-file-view:
  - jar
  - gz
  - dat
  - dat_old
  - lock
  - mca

#You can choose between 2 languages ​​for the moment, French (FR) or English (ENG)

# /!\ Warning if you change language the messages and the configuration will be deleted and replace with the one in the language select /!\

#The plugin is not in your language? Personalize the entire plugin messages and
#share them on the plugin page for everyone to enjoy!
lang: 'ENG'

#if you want change lang on restart, change to true and don't touch after.
changeonstart: false
